package com.islands.games.dicelegend.moves

import groovy.transform.Canonical

@Canonical
/**
 * An effect generated by a {@link Move}. Can apply to the user or the foe, determined by whether or not ${@link Effect#trap}
 * is set, with true meaning it applies to the foe and vice versa.
 */
class Effect {
    String name
    boolean endTurn
    boolean stackable
    boolean trap

    def conditions = []
    def actions = []

    def watchStackName

    Effect(String name) {
        this.name = name
    }

    /**
     * Determine whether or not a {@link Move} meets the conditions of this Effect.
     * @param move The Move to check.
     * @return True if all conditions are met, false otherwise.
     */
    boolean valid(Move move) {
        def valid = true
        conditions.each {
            if(!it(move)) {
                valid = false
            }
        }
        valid
    }

    /**
     * Generate a copy of a {@link Move} with all actions applied to it.
     * @param move The Move to copy.
     * @return The resulting Move, modified per the Effect.
     */
    Move trigger(Move move) {
        move.clone(actions)
    }
}
